services:
  quotevault:
    build: ./app
    container_name: quotevault
    restart: unless-stopped
    env_file:
      - path: .env
        required: false
    ports:
      - "8080:8080"
    volumes:
      - ./data:/data
